# Generated by Django 4.2.2 on 2023-08-16 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('regid', models.AutoField(primary_key=True, serialize=False)),
                ('catname', models.CharField(max_length=50, unique=True)),
                ('caticonname', models.CharField(max_length=50)),
            ],
        ),
    ]
