# Generated by Django 4.2.2 on 2024-05-21 00:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0005_rename_pbprice_product_p_bprice_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='p_bprice',
            new_name='pbprice',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_description',
            new_name='pdescription',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_iconname',
            new_name='piconname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_id',
            new_name='pid',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='p_title',
            new_name='ptitle',
        ),
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
