# Generated by Django 4.2.2 on 2023-08-07 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('txnid', models.AutoField(primary_key=True, serialize=False)),
                ('uid', models.CharField(max_length=50)),
                ('amt', models.IntegerField()),
                ('info', models.CharField(max_length=50)),
            ],
        ),
    ]
